# Generated by Django 3.2.8 on 2024-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0023_rename_item_inventoryitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='minimum_unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_per_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
