# Generated by Django 3.2.8 on 2024-05-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0024_auto_20240529_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLimit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_id', models.CharField(max_length=32)),
                ('minimum_unit', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_app.inventoryitem')),
            ],
        ),
    ]
