# Generated by Django 3.2.8 on 2024-05-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0025_locationlimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationlimit',
            name='item',
        ),
        migrations.AddField(
            model_name='locationlimit',
            name='item_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='location_limits', to='inventory_app.inventoryitem'),
            preserve_default=False,
        ),
    ]
