# Generated by Django 3.2.8 on 2026-01-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0026_auto_20240530_1033'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationlimit',
            unique_together={('item_id', 'location_id')},
        ),
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('allocated_quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory_app.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationFulfillment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='inventory_app.inventoryallocation')),
            ],
        ),
    ]
