# Generated by Django 3.2.8 on 2026-01-09 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0027_auto_20260109_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryallocation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='expected_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
