# Generated by Django 3.2.8 on 2026-01-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0028_auto_20260109_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationfulfillment',
            name='withdrawal_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryallocation',
            name='reference',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
