# Generated by Django 3.2.8 on 2026-02-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0029_auto_20260121_1026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryallocation',
            unique_together={('item_id', 'reference')},
        ),
    ]
